export const interactiveLayerIds = ['clicktargetAndStatsTotal']

export const layers = [
  {
    type: 'line',
    id: 'index_casing',
    layout: {
      'line-cap': 'round',
      'line-sort-key': [
        'case',
        ['match', ['get', 'proc_mandatory'], ['use_sidepath', 'optional_sidepath'], true, false],
        0,
        [
          'match',
          ['get', 'way_type'],
          ['bicycle road', 'shared bus lane', 'shared traffic lane', 'shared road'],
          true,
          false,
        ],
        2,
        1,
      ],
    },
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 1.4, 10, 1.4, 22, 16],
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        ['match', ['get', 'side'], ['right'], 1, ['left'], -1, 0],
        10,
        ['match', ['get', 'side'], ['right'], 1, ['left'], -1, 0],
        22,
        ['match', ['get', 'side'], ['right'], 12, ['left'], -12, 0],
      ],
      'line-color': [
        'match',
        ['get', 'way_type'],
        [
          'shared path',
          'crossing',
          'shared footway',
          'cycle lane (protected)',
          'cycle track',
          'segregated path',
          'link',
          'cycle path',
          'track or service',
        ],
        'rgb(125, 125, 125)',
        'rgb(0, 0, 0)',
      ],
    },
  },
  {
    type: 'line',
    id: 'index_gap_background',
    layout: {
      'line-cap': 'round',
    },
    paint: {
      'line-color': [
        'step',
        ['get', 'index'],
        'rgb(155, 9, 9)',
        10,
        'rgb(201, 41, 3)',
        20,
        'rgb(245, 105, 24)',
        30,
        'rgb(251, 185, 56)',
        40,
        'rgb(201, 239, 52)',
        50,
        'rgb(116, 254, 93)',
        60,
        'rgb(27, 229, 181)',
        70,
        'rgb(53, 171, 248)',
        80,
        'rgb(70, 98, 216)',
        90,
        'rgb(28, 59, 180)',
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 1, 10, 1, 22, 12],
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        ['match', ['get', 'side'], ['right'], 1, ['left'], -1, 0],
        10,
        ['match', ['get', 'side'], ['right'], 1, ['left'], -1, 0],
        22,
        ['match', ['get', 'side'], ['right'], 12, ['left'], -12, 0],
      ],
    },
  },
  {
    type: 'line',
    id: 'index_main_colour',
    layout: {
      'line-sort-key': [
        'step',
        ['get', 'index'],
        3,
        10,
        10,
        20,
        20,
        30,
        30,
        40,
        40,
        50,
        50,
        60,
        60,
        70,
        70,
        80,
        80,
        90,
        90,
      ],
    },
    paint: {
      'line-color': [
        'step',
        ['get', 'index'],
        'rgb(155, 9, 9)',
        10,
        'rgb(201, 41, 3)',
        20,
        'rgb(245, 105, 24)',
        30,
        'rgb(251, 185, 56)',
        40,
        'rgb(201, 239, 52)',
        50,
        'rgb(116, 254, 93)',
        60,
        'rgb(27, 229, 181)',
        70,
        'rgb(53, 171, 248)',
        80,
        'rgb(70, 98, 216)',
        90,
        'rgb(28, 59, 180)',
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 1, 10, 1, 22, 12],
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        ['match', ['get', 'side'], ['right'], 1, ['left'], -1, 0],
        10,
        ['match', ['get', 'side'], ['right'], 1, ['left'], -1, 0],
        22,
        ['match', ['get', 'side'], ['right'], 12, ['left'], -12, 0],
      ],
    },
  },
  {
    type: 'line',
    id: 'lane markings solid',
    layout: {
      'line-sort-key': [
        'step',
        ['get', 'index'],
        3,
        10,
        10,
        20,
        20,
        30,
        30,
        40,
        40,
        50,
        50,
        60,
        60,
        70,
        70,
        80,
        80,
        90,
        90,
      ],
    },
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.15, 10, 0.15, 22, 1.8],
      'line-color': 'rgb(255, 255, 255)',
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        ['match', ['get', 'side'], ['right'], 0.6, ['left'], -0.6, 0],
        10,
        ['match', ['get', 'side'], ['right'], 0.6, ['left'], -0.6, 0],
        22,
        ['match', ['get', 'side'], ['right'], 8, ['left'], -8, 0],
      ],
    },
    filter: [
      'all',
      ['match', ['get', 'side'], ['left', 'right'], true, false],
      ['match', ['get', 'way_type'], ['cycle lane (exclusive)'], true, false],
    ],
  },
  {
    type: 'line',
    id: 'lane markings dashed',
    layout: {
      'line-sort-key': [
        'step',
        ['get', 'index'],
        3,
        10,
        10,
        20,
        20,
        30,
        30,
        40,
        40,
        50,
        50,
        60,
        60,
        70,
        70,
        80,
        80,
        90,
        90,
      ],
    },
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.15, 10, 0.15, 22, 1.8],
      'line-color': 'rgb(255, 255, 255)',
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        ['match', ['get', 'side'], ['right'], 0.6, ['left'], -0.6, 0],
        10,
        ['match', ['get', 'side'], ['right'], 0.6, ['left'], -0.6, 0],
        22,
        ['match', ['get', 'side'], ['right'], 8, ['left'], -8, 0],
      ],
      'line-dasharray': [3, 3],
    },
    filter: [
      'all',
      ['match', ['get', 'side'], ['left', 'right'], true, false],
      [
        'match',
        ['get', 'way_type'],
        ['cycle lane (advisory)', 'cycle lane (central)', 'shared bus lane', 'crossing'],
        true,
        false,
      ],
    ],
  },
  {
    type: 'line',
    id: 'track markings',
    layout: {
      'line-sort-key': [
        'step',
        ['get', 'index'],
        3,
        10,
        10,
        20,
        20,
        30,
        30,
        40,
        40,
        50,
        50,
        60,
        60,
        70,
        70,
        80,
        80,
        90,
        90,
      ],
    },
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.2, 10, 0.2, 22, 2],
      'line-color': 'rgb(150, 150, 150)',
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        0,
        ['match', ['get', 'side'], ['right'], 0.6, ['left'], -0.6, 0],
        10,
        ['match', ['get', 'side'], ['right'], 0.6, ['left'], -0.6, 0],
        22,
        ['match', ['get', 'side'], ['right'], 8, ['left'], -8, 0],
      ],
    },
    filter: [
      'all',
      ['match', ['get', 'side'], ['left', 'right'], true, false],
      [
        'match',
        ['get', 'way_type'],
        ['shared path', 'shared footway', 'cycle track', 'segregated path', 'cycle path'],
        true,
        false,
      ],
    ],
  },
]
